export const TODO_TASK_POST_START = "TODO_TASK_POST_START";
export const TODO_TASK_POST_SUCCESS = "TODO_TASK_POST_SUCCESS";
export const TODO_TASK_POST_FAIL = "TODO_TASK_POST_FAIL";

export const GET_TODO_TASK_START = "GET_TODO_TASK_START";
export const GET_TODO_TASK_SUCCESS = "GET_TODO_TASK_SUCCESS";
export const GET_TODO_TASK_FAIL = "GET_TODO_TASK_FAIL";

export const DELETE_TODO_TASK_START = "DELETE_TODO_TASK_START";
export const DELETE_TODO_TASK_SUCCESS = "DELETE_TODO_TASK_SUCCESS";
export const DELETE_TODO_TASK_FAIL = "DELETE_TODO_TASK_FAIL";

export const RESET_ALERT_MESSAGE = "RESET_ALERT_MESSAGE";